id: P5341D53D
initial_creation_type: input
source_metadata:
  title: Adzom Gyalse Series
  language: en
  description: 'Texts by and about Adzom Gyalse Gyurme Dorje (a ''dzoms rgyal sras
    ’gyur med rdo rje, 1895–1969):'
  volume:
    90fddd7b5d9f482ba84d80be780f00a0:
      title: 'Advice for Beginners: How to Overcome Obstacles to Meditation'
      parent: Advice
    85b87dbdab6749f2ade7ca7b770f3f1f:
      title: A Concise Explanation of Gaṇacakra
      parent: Commentaries
    6e3096402308424d8d13ae0154bb150c:
      title: Notes on the Heart-Essence Practices of the Channels and Wind-Energies
      parent: Tsa Lung
created_at: '2022-02-28T22:35:30.538980'
last_modified_at: '2022-02-28T22:35:30.538987'
